name: weather_app_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.3.0
  flutter_bloc: ^8.1.1
  location: ^4.2.0
#  intl: ^0.17.0
  easy_localization: ^3.0.1
  lottie: ^2.3.2
  zoom_tap_animation: ^1.1.0
  dio: ^4.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.7.0
  equatable: ^2.0.5
  flutter_svg: ^1.1.1+1
  shimmer: ^2.0.0
  animated_icon_button: ^1.0.2
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  min_sdk_android: 21


flutter_native_splash:
  image: assets/images/app_logo.png
  color: "#FFFFFF"
  fullscreen: true
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/app_logo.png
    - assets/images/russia.png
    - assets/images/usa.png
    - assets/images/uzbek.png
    - assets/svgs/
    - assets/translations/en-EN.json
    - assets/translations/ru-RU.json
    - assets/translations/uz-UZ.json
    - assets/lotties/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 900